Repository House-of-M/HacktoberFest_2022, pull requests merged in 2022-10, with the labels that each got.

#2 Added Rock_Paper_Scissors
  projects/README.md
  projects/Rock_Paper_Scissors/app.js
  projects/Rock_Paper_Scissors/index.html
  projects/Rock_Paper_Scissors/style.css
Labels: hacktoberfest, hacktoberfest-accepted, javascript

#3 Added GitHub Profile Card web project
  projects/GitHub Profile Card/README.md
  projects/GitHub Profile Card/index.html
  projects/GitHub Profile Card/script.js
  projects/GitHub Profile Card/style.css
  projects/README.md
Labels: css, hacktoberfest, html, javascript

#4 Adding Discord Bot python project
  .gitignore
  projects/Discord Bot/README.md
  projects/Discord Bot/bot.py
  projects/Discord Bot/main.py
  projects/Discord Bot/responses.py
  projects/README.md
Labels: hacktoberfest, hacktoberfest-accepted, python

#5 Adding python project
  projects/Python Login GUI/README.md
  projects/Python Login GUI/app.py
  projects/Python Login GUI/bkg.jpg
  projects/README.md
Labels: hacktoberfest, hacktoberfest-accepted, python

#6 Marvel Comics python app
  projects/Marvel Comics Python Search App/README.md
  projects/Marvel Comics Python Search App/app.py
  projects/README.md
Labels: hacktoberfest, hacktoberfest-accepted, python

#7 1st HacktoberFest PR
  projects/NLP_Naive_Bayes_Classifier/Built_Naive_Bayes_NLP.ipynb
  projects/NLP_Naive_Bayes_Classifier/doc
Labels: hacktoberfest, hacktoberfest-accepted, Jupyter Notebook, python

#8 2nd contribution
  projects/ML for bio/ML_on_cell_expression_data.ipynb
  projects/ML for bio/README.md
Labels: hacktoberfest, hacktoberfest-accepted, Jupyter Notebook, python

#9 Update README.md
  projects/README.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#10 3rd PR
  projects/Text_categorization/README.md
  projects/Text_categorization/Text_categorization.ipynb
Labels: hacktoberfest, hacktoberfest-accepted, Jupyter Notebook

#11 4th PR
  projects/Image_Processing/Image_Processing_w_Fourrier.ipynb
  projects/Image_Processing/README.md
  projects/Image_Processing/TP4_utils.py
Labels: hacktoberfest, hacktoberfest-accepted, Jupyter Notebook, python

#12 Upload Wavelets lab
  projects/Image_Processing/Image_Processing_w_Wavelets.ipynb
Labels: hacktoberfest, Jupyter Notebook, python

#13 Adding webdev project
  projects/Personal landing page/README.md
  projects/Personal landing page/index.html
  projects/Personal landing page/reset.css
  projects/Personal landing page/style.css
Labels: hacktoberfest, hacktoberfest-accepted, html

#15 Fixing project name
  projects/README.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted
